// old_src/App.svelte
<script>
  import Worktable from "./lib/Worktable.svelte";
  import userPrompt from "./lib/user-prompt.js";
  import CodeDisplay from "./lib/CodeDisplay.svelte";
  import ForceRefresh from "./lib/forceRefresh.svelte";

  let code = "";
  let error = false;
  $: {
    //Set code to the contents of Worktable file whenever Worktable.svelte is updated
    fetch("src/lib/Worktable.txt")
      .then((res) => res.text())
      .then((text) => (code = text));
  }
  $: {
    console.log(error);
  }
</script>

<main>
  <div class="header">
    <div class="user-prompt">
      Prompt: {userPrompt}
    </div>
  </div>
  <div class="contentPanels">
    <div class="panel">
      <div class="panelHeader">Code</div>
      <CodeDisplay {code} />
    </div>
    <div class="panel">
      <div class="panelHeader">Output</div>
      {#if !error}
        <Worktable
          on:componentError={() => {
            error = true;
            console.log(error);
          }}
        />
      {/if}
    </div>
  </div>
</main>

<style>
  main {
    display: flex;
    flex-direction: column;
    justify-content: flex-start;
    align-items: center;
    height: 100%;
    width: 100%;
  }

  .header {
    display: flex;
    justify-content: center;
    align-items: center;
    width: 100%;
    height: 10vh;
  }

  .user-prompt {
    font:
      1.5rem "Source Sans Pro",
      monospace;
  }

  .contentPanels {
    display: grid;
    grid-template-columns: 7fr 3fr;
    width: 100%;
    height: 90vh;
    /* margin between columns: */
    gap: 1rem;
    /* columns should be each 50% of the width of the parent container */
  }

  .contentPanels > * {
    width: 100%;
  }

  .panel {
    display: flex;
    flex-direction: column;
    justify-content: flex-start;
    align-items: center;
    width: 100%;
    border: 2px solid black;
    border-radius: 1rem;
    margin: 1rem;
  }

  .panelHeader {
    font:
      1.5rem "Courier New",
      Courier,
      monospace;
    margin: 1rem;
  }
</style>

// autowebsite/src/app/page.jsx
'use client';

import React, { useState, useEffect } from "react";
import Worktable from "./lib/Worktable";
import userPrompt from "./lib/user-prompt";
import CodeDisplay from "./lib/CodeDisplay";
import "./page.css";

const App = () => {
  const [code, setCode] = useState("console.log('Hello world')");
  const [error, setError] = useState(false);

  useEffect(() => {
    fetch("Worktable.txt")
      .then((res) => res.text())
      .then((text) => setCode(text));
  }, []);

  return (
    <main>
      <div className="header">
        <div className="user-prompt">Prompt: {userPrompt}</div>
      </div>
      
      <div className="contentPanels">
        <div className="panel">
          <div className="panelHeader">Code</div>
          <div className="code">
            <CodeDisplay code={code} />
          </div>
        </div>
        <div className="panel">
          <div className="panelHeader">Output</div>
          <div className="component">
            <ErrorBoundary>
              {!error && <Worktable onError={() => setError(true)} />}
              {error && <div class="error-container">
                <div class="error-text">Error in generation</div>
              </div>}
            </ErrorBoundary>
          </div>
        </div>
      </div>
      <div className="fixed bottom-0 right-0 p-2 bg-gray-800 text-white text-sm rounded-tl-md text-2xl">
        <div>Keyphrases:</div>
          <ul>
            <li>Delete all</li>
            <li>Fix error</li>
          </ul>
      </div>
    </main>
  );
};

class ErrorBoundary extends React.Component {
  constructor(props) {
    super(props);
    this.state = { hasError: false };
  }

  static getDerivedStateFromError(error) {
    return { hasError: true };
  }

  componentDidCatch(error, errorInfo) {
    console.error("Error caught:", error, errorInfo);
  }

  render() {
    if (this.state.hasError) {
      return <div class="w-full h-full flex justify-center items-center">
      <div class="text-4xl">Error in generation ☹️</div>
    </div>;
    }
    return this.props.children;
  }
}

export default App;
